name: dagger

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Dagger
        uses: dagger/dagger-for-github@v2
        with:
          workdir: ./go-project
          args: do lint

  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Dagger
        uses: dagger/dagger-for-github@v2
        with:
          workdir: ./go-project
          args: do test